name: Build feed from my links

on:
  workflow_dispatch: {}
  # Если нужно автообновление по расписанию — раскомментируй:
  # schedule:
  #   - cron: "0 */3 * * *"   # каждые 3 часа

# чтобы параллельные запуски не мешали друг другу
concurrency:
  group: manual-feed
  cancel-in-progress: false

# даём экшену право коммитить в репозиторий
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # важно для pull --rebase

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      # парсит data/manual_products.csv -> data/products.json
      - name: Parse manual links
        run: npx ts-node scripts/parse_manual.ts

      # ✅ ключевой шаг: подтянуть последние изменения перед пушем,
      # чтобы не было ошибки "rejected (fetch first)"
      - name: Commit & push feed (with rebase)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/products.json
          git commit -m "feed: update from manual links" || echo "No changes to commit"

          # если нечего пушить — выходим
          if [ -z "$(git diff --cached --name-only)" ]; then
            echo "No staged changes. Skip push."
            exit 0
          fi

          # тянем последнее и кладём наш коммит поверх
          git pull --rebase origin main || true

          # пушим
          git push origin main
