name: Build feed from my links

on:
  workflow_dispatch: {}
  # Если нужно автообновление — сними комментарий:
  # schedule:
  #   - cron: "0 */3 * * *"

concurrency:
  group: manual-feed
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # нужно для pull --rebase

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show Node & NPM versions
        run: |
          node -v
          npm -v

      # ✅ самый надёжный способ установки зависимостей
      - name: Install deps (robust)
        run: |
          # иногда npm глючит на ci — ставим обычным install с флагами
          npm install --no-audit --no-fund
        env:
          # на всякий случай фиксируем реестр
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/

      - name: Install Playwright Chromium
        run: |
          npx playwright install --with-deps chromium

      # ваш парсер: читает data/manual_products.csv -> пишет data/products.json
      - name: Parse manual links
        run: npx ts-node scripts/parse_manual.ts

      # подтянем последние изменения и запушим результат
      - name: Commit & push feed (with rebase)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/products.json
          # если изменений нет — коммит упадёт, поэтому мягко продолжаем
          git commit -m "feed: update from manual links" || echo "No changes to commit"

          # если нечего пушить — выходим
          if [ -z "$(git diff --cached --name-only)" ]; then
            echo "No staged changes. Skip push."
            exit 0
          fi

          # подтянуть свежие коммиты и положить наш поверх
          git pull --rebase origin main || true

          git push origin main
