name: Temu Auto Feed (3h)

on:
  schedule:
    - cron: "0 */3 * * *"   # каждые 3 часа
  workflow_dispatch: {}     # запуск вручную

concurrency:
  group: temu-feed-main
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npx ts-node scraper/temu_scraper.ts

      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Temu products feed [skip ci]"
          branch: main
          file_pattern: data/products.json
